# Terraform Pipeline
trigger:
  branches:
    include:
      - main  # Trigger pipeline on commits to the main branch

pool:
  name: 'Default'

variables:
  terraformVersion: '1.5.5'  # Specify the Terraform version
  azureServiceConnection: 'intech'  # Azure service connection name
  backendResourceGroup: 'skink-rg'
  backendStorageAccount: 'skinktfstate'  # Remote backend storage account
  backendContainer: 'tfstate'  # Remote backend storage container
  backendKey: 'terraform.tfstate'  # State file name in remote backend

steps:
  - task: TerraformInstaller@0  # Install Terraform
    inputs:
      terraformVersion: $(terraformVersion)
  
  - checkout: self  # Check out the repository

  - task: TerraformTaskV2@2
    inputs:
      provider: 'azurerm'  # Azure provider
      command: 'init'  # Initialize Terraform
      backendServiceArm: $(azureServiceConnection)
      backendAzureRmResourceGroupName: $(backendResourceGroup)
      backendAzureRmStorageAccountName: $(backendStorageAccount)
      backendAzureRmContainerName: $(backendContainer)
      backendAzureRmKey: $(backendKey)
      workingDirectory: 'terraform'  # Set the working directory

  - task: TerraformTaskV2@2
    inputs:
      provider: 'azurerm'
      command: 'plan'  # Run terraform plan
      environmentServiceNameAzureRM: $(azureServiceConnection)
      commandOptions: '-out=plan.tfplan'  # Output the plan to a file
      workingDirectory: 'terraform'  # Set the working directory

  - task: TerraformTaskV2@2
    inputs:
      provider: 'azurerm'
      command: 'apply'  # Run terraform apply
      environmentServiceNameAzureRM: $(azureServiceConnection)
      commandOptions: 'plan.tfplan'  # Apply the plan from the file
      workingDirectory: 'terraform'  # Set the working directory

  - task: PublishBuildArtifacts@1  # Optional: Publish artifacts (like plan or state files)
    inputs:
      pathToPublish: './terraform/terraform.tfstate'
      artifactName: 'terraform'
      publishLocation: 'Container'